version: '3'

services:
  db:
    image: mysql
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: MY_ROOT_PASS
      MYSQL_DATABASE: my_db
      MYSQL_USER: chand
      MYSQL_PASSWORD: chand
    ports:
      - "6603:3306"
  web:
    image: 31052007/mysql_php_application
    pull_policy: always
    # build:
    #   context: ./php_sample_code
    #   dockerfile: Dockerfile
    container_name: php_web
    depends_on:
      - db
    volumes:
      - ./php_sample_code/:/var/www/html/
    ports:
      - "8100:80"
    stdin_open: true
    tty: true
    # env_file:
    #   - credentials.env
    environment:
      DB: ${DB}
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
      
